# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DebugWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DebugWindow(object):
    def setupUi(self, DebugWindow):
        DebugWindow.setObjectName("DebugWindow")
        DebugWindow.resize(219, 204)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        DebugWindow.setFont(font)
        self.widget = QtWidgets.QWidget(DebugWindow)
        self.widget.setGeometry(QtCore.QRect(30, 20, 168, 101))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setMaximum(250)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 3, 0, 1, 2)
        self.Slider_Toggle_Label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Slider_Toggle_Label.setFont(font)
        self.Slider_Toggle_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Slider_Toggle_Label.setObjectName("Slider_Toggle_Label")
        self.gridLayout.addWidget(self.Slider_Toggle_Label, 1, 0, 1, 1)
        self.Debug_Toggle_Label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Debug_Toggle_Label.setFont(font)
        self.Debug_Toggle_Label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Debug_Toggle_Label.setObjectName("Debug_Toggle_Label")
        self.gridLayout.addWidget(self.Debug_Toggle_Label, 0, 0, 1, 1)
        self.Slider_Value_Label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.Slider_Value_Label.setFont(font)
        self.Slider_Value_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Slider_Value_Label.setObjectName("Slider_Value_Label")
        self.gridLayout.addWidget(self.Slider_Value_Label, 3, 2, 1, 1)
        self.Debug_Toggle_Box = QtWidgets.QCheckBox(self.widget)
        self.Debug_Toggle_Box.setText("")
        self.Debug_Toggle_Box.setObjectName("Debug_Toggle_Box")
        self.gridLayout.addWidget(self.Debug_Toggle_Box, 0, 1, 1, 2)
        self.Slider_Toggle_Box = QtWidgets.QCheckBox(self.widget)
        self.Slider_Toggle_Box.setEnabled(False)
        self.Slider_Toggle_Box.setText("")
        self.Slider_Toggle_Box.setObjectName("Slider_Toggle_Box")
        self.gridLayout.addWidget(self.Slider_Toggle_Box, 1, 1, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 3)
        self.Slider_Toggle_Label.setBuddy(self.Slider_Toggle_Box)
        self.Debug_Toggle_Label.setBuddy(self.Debug_Toggle_Box)
        self.Slider_Value_Label.setBuddy(self.horizontalSlider)

        self.retranslateUi(DebugWindow)
        self.horizontalSlider.valueChanged['int'].connect(self.Slider_Value_Label.setNum)
        self.Slider_Toggle_Box.toggled['bool'].connect(self.horizontalSlider.setEnabled)
        self.Debug_Toggle_Box.toggled['bool'].connect(self.Slider_Toggle_Box.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DebugWindow)

    def retranslateUi(self, DebugWindow):
        _translate = QtCore.QCoreApplication.translate
        DebugWindow.setWindowTitle(_translate("DebugWindow", "Debug Window"))
        self.Slider_Toggle_Label.setText(_translate("DebugWindow", "Slider Toggle: "))
        self.Debug_Toggle_Label.setText(_translate("DebugWindow", "Debug Mode: "))
        self.Slider_Value_Label.setText(_translate("DebugWindow", "0"))

class DebugWindow(QtWidgets.QDialog, Ui_DebugWindow):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
